// <auto-generated />
using System;
using CloudTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace CloudTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudTest.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("CloudTest.Models.TestSuite", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("TestSuites");
            });

            modelBuilder.Entity("CloudTest.Models.TestCase", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("ExpectedBehavior").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("TestSuiteId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("TestSuiteId");
                b.ToTable("TestCases");
            });

            modelBuilder.Entity("CloudTest.Models.TestRun", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("ExecutedAt").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("TestRuns");
            });

            modelBuilder.Entity("CloudTest.Models.TestResult", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Status").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<long>("ResponseTimeMs").HasColumnType("bigint");
                b.Property<DateTime>("RecordedAt").HasColumnType("datetime2");
                b.Property<int>("TestCaseId").HasColumnType("int");
                b.Property<int>("TestRunId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("TestRunId", "TestCaseId");
                b.ToTable("TestResults");
            });

            modelBuilder.Entity("CloudTest.Models.TestCase", b =>
            {
                b.HasOne("CloudTest.Models.TestSuite", "TestSuite")
                    .WithMany("TestCases")
                    .HasForeignKey("TestSuiteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("TestSuite");
            });

            modelBuilder.Entity("CloudTest.Models.TestRun", b =>
            {
                b.HasOne("CloudTest.Models.User", "User")
                    .WithMany("TestRuns")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("CloudTest.Models.TestResult", b =>
            {
                b.HasOne("CloudTest.Models.TestCase", "TestCase")
                    .WithMany("TestResults")
                    .HasForeignKey("TestCaseId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CloudTest.Models.TestRun", "TestRun")
                    .WithMany("TestResults")
                    .HasForeignKey("TestRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("TestCase");
                b.Navigation("TestRun");
            });
#pragma warning restore 612, 618
        }
    }
}
